### ISSUE TITLE
Documentation staging area and releases

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#162]
Right now the release process of the documentation is the following: just merge on main and release.

It would make reasonably simpler to develop the documentation if we had a staging area, say the `main` branch, where we merge PRs. The main branch could be published to a "private domain", which we can access for testing that everything works fine, and then during releases we point `docs.restate.dev` to a specific git tag.

**Comment by gvdongen** [comment]
Just trying to understand this first. Why do we need this? If you create a PR, you see a test deployment right?
And if you merge to main, it deploys the new version (you don't need to release).

**Comment by slinkydeveloper** [comment]
> And if you merge to main, it deploys the new version (you don't need to release).

That's exactly what i would like to avoid, so when developing new features we can merge the docs, iterate on it, and not show it to the user in the meantime. This would make the release process a tad bit easier and faster, because the doc would be already (mostly) in shape when the release day comes.

**Comment by slinkydeveloper** [comment]
Giselle and I discussed about using a new branch `dev` as staging area, so the workflow would be the following:

* PRs will point to `dev`
* `dev` is deployed continuosly on `staging.docs.restate.dev` or something like that
* When releasing, `dev` is merged on `main` and tagged/released.
* `main` is deployed continuosly on `docs.restate.dev` like it currently is

**Comment by jackkleeman** [comment]
https://docs.restate.dev -> `production` branch
https://main--docsrestatedev.netlify.app -> `main` branch

We are not able to password protect only one of these without giving netlify more money. Well, technically I can probably do it with an edge function for free. But I suggest we don't bother :)

**Comment by jackkleeman** [comment]
francesco and i agreed a process of tagging releases on main and pushing them to production branch to deploy a new release

**Comment by slinkydeveloper** [comment]
> We are not able to password protect only one of these without giving netlify more money. Well, technically I can probably do it with an edge function for free. But I suggest we don't bother :)

I think it's fine, some users that are on snapshots might be ok with looking at the staging docs
