### ISSUE TITLE
Logging on Lambda with log4j2

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#184]
Log4j2 has custom appenders for lambda, that the aws docs encourages to use https://docs.aws.amazon.com/lambda/latest/dg/java-logging.html#java-logging-log4j2. We should perhaps investigate those and see whether we need to document them.

**Comment by slinkydeveloper** [comment]
cc @pcholakov

**Comment by pcholakov** [comment]
Agreed, this makes sense! Perhaps in the future, we can inject some of these into a higher-level CDK construct for bundling Java- or Kotlin-based Restate Lambda handlers: point it at a class file, it turns it into a Lambda deployment.

**Comment by slinkydeveloper** [comment]
Note for myself: in the template projects configure aws log4j2 logging directly, rather than console logger.

**Comment by pcholakov** [comment]
After https://github.com/restatedev/examples/pull/50 is merged, we can update all the other Lambda examples to use the same/similar log4j2 config.

**Comment by slinkydeveloper** [comment]
Solved
