### ISSUE TITLE
Do we need the examples page in the documentation?

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#192]
Do we need this page? https://main.documentation-beg.pages.dev/examples

Could we just link the `Examples` in the sidebar to https://github.com/restatedev/examples? Maybe even place a redirect from https://docs.restate.dev/examples to https://github.com/restatedev/examples

I fear that this page will quickly get outdated

**Comment by slinkydeveloper** [comment]
WDYT @gvdongen?

**Comment by gvdongen** [comment]
Fair, I think this is a good idea
