### ISSUE TITLE
Document time bounds of service invocations

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/documentation#216]
The system imposes some time bounds on how long an invocation can be running w/o generating new journal entries. We should document the behavior and explain how it can be configured via `worker.invoker.inactivity_timeout` and `worker.invoker.abort_timeout`.

**Comment by gvdongen** [comment]
I would say:
- Add the configurations to https://docs.restate.dev/restate/configuration
- I think we are missing a more general explanation of journaling/suspension/replay in the docs... I think this would fit on that page as a note... Maybe a new `Overview` page under SDKs... 
What do you think?

**Comment by slinkydeveloper** [comment]
> Add the configurations to https://docs.restate.dev/restate/configuration

This is already there.

> I think we are missing a more general explanation of journaling/suspension/replay in the docs... I think this would fit on that page as a note... Maybe a new Overview page under SDKs...

It's ok for me to start with that, but i'm not sure i would immediately look in that page... Maybe https://docs.restate.dev/services/deployment/general?

**Comment by gvdongen** [comment]
But it doesn't have much to do with deployment of services? Then I'd sooner place it on the invocation page: https://docs.restate.dev/services/invocation as a note
