### ISSUE TITLE
Attach to an existing invocation/get output

### ISSUE THREAD

**Issue by slinkydeveloper** [restatedev/documentation#387]
There are now 2 new operations in the ingress related to invocations:

* Attach: attach to a running invocation and wait for the output. In case the invocation is already completed, it immediately replies back with the result. If the invocation doesn't exist, replies with 404
* Output: try to get the output now. In case the invocation is already completed, it immediately replies back with the result. If the invocation doesn't exist, replies with 404. If the invocation is still running, it replies with 470

To specify the "query" to the invocation, there are three ways:

* Provide the invocation id directly: `GET /restate/invocation/:invocationId/attach` or `GET /restate/invocation/:invocationId/output`
* Provide the combination of invocation target and idempotency key: `GET /restate/invocation/:svcName/:svcHandler/:idempotencyKey/attach` or `GET /restate/invocation/:virtualObject/:key/:handler/:idempotencyKey/attach`, `GET /restate/invocation/:svcName/:svcHandler/:idempotencyKey/output` or `GET /restate/invocation/:virtualObject/:key/:handler/:idempotencyKey/output`
* For workflows only, provide the combination workflow name and workflow key: `GET /restate/workflow/:workflowName/:workflowKey/attach` or `GET /restate/workflow/:workflowName/:workflowKey/output`

**Comment by gvdongen** [comment]
Fixed in https://github.com/restatedev/documentation/pull/388
