### ISSUE TITLE
Doc: Write programming model section

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/documentation#4]
## What to write here

In addition to what has been written:

* A word on the design of Restate: meta + worker and their responsabilities
* Some diagram of how Restate fits in the system (e.g. Restate in the middle, some services around it, possible ingress options, ...)
* Maybe programming model is not the right name. Maybe overview or "The essentials" would be better. TBD...

**Comment by gvdongen** [comment]
@tillrohrmann Should we close this?

**Comment by gvdongen** [comment]
Will be covered by #265
