### ISSUE TITLE
Doc: Write resiliency section

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/documentation#8]
## What to write here

Resilience of service invocations:

* guarantees
* retries
* What happens when an invocation fails: network failure vs user code (vs possible SDK bugs)
* retries + side effects: how users should use retry logic together with side effects to
* configs we have for retries etc

Runtime

* What happens in case of a failure of worker/meta: current guarantees and maybe mentioning that will become distributed at later point in time

**Comment by gvdongen** [comment]
@tillrohrmann Should we close this?

**Comment by gvdongen** [comment]
Will be covered by #265
